import type { Metadata } from "next";
import { Noto_Sans, Dela_Gothic_One } from "next/font/google";
import "../style/globals.css";

const notoSans = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
});
const dela = Dela_Gothic_One({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className || dela.className} `}
      >
        {children}
      </body>
    </html>
  );
}
